# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e026de3b99f72980aad95c55f9f76476e5a2208df22d9026ecfe31e8a149f45d7da2289398b6616daf0e17b400e3ac8c93fc19fdb2e619c9a7fc96b9c856da97

test:
  secret_key_base: 84e31f42a0151c2163b50c8245ac1b514e1beccec42230867706c837f12fc2f03dae6dac4b4d85a69b4852e85217d0c8528513cb7e1f94bcb0bc56485316ec0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
